-- THIS IS AN AUTO GENERATED SCRIPT IN ORDER TO DETECT FUNCTIONAL DEPENDENCIES
-- AUTHOR: ANDREAS NICOLAJ TIETGEN

SELECT 'Projects: ID --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: ID --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: ID --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: ID --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: ID --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.MID) > 1
) X;

SELECT 'Projects: ID --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.ID
FROM Projects P
GROUP BY P.ID
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: PID --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: PID --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: PID --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: PID --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: PID --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.MID) > 1
) X;

SELECT 'Projects: PID --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PID
FROM Projects P
GROUP BY P.PID
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: SID --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: SID --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: SID --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: SID --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: SID --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.MID) > 1
) X;

SELECT 'Projects: SID --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SID
FROM Projects P
GROUP BY P.SID
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: SN --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: SN --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: SN --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: SN --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: SN --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.MID) > 1
) X;

SELECT 'Projects: SN --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.SN
FROM Projects P
GROUP BY P.SN
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: PN --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: PN --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: PN --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: PN --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: PN --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.MID) > 1
) X;

SELECT 'Projects: PN --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.PN
FROM Projects P
GROUP BY P.PN
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: MID --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: MID --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: MID --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: MID --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: MID --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: MID --> MN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MID
FROM Projects P
GROUP BY P.MID
HAVING COUNT(DISTINCT P.MN) > 1
) X;

SELECT 'Projects: MN --> ID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.ID) > 1
) X;

SELECT 'Projects: MN --> PID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.PID) > 1
) X;

SELECT 'Projects: MN --> SID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.SID) > 1
) X;

SELECT 'Projects: MN --> SN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.SN) > 1
) X;

SELECT 'Projects: MN --> PN' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.PN) > 1
) X;

SELECT 'Projects: MN --> MID' AS FD,
CASE WHEN COUNT(*)=0 THEN 'MAY HOLD'
ELSE 'does not hold' END AS VALIDITY
FROM (
SELECT P.MN
FROM Projects P
GROUP BY P.MN
HAVING COUNT(DISTINCT P.MID) > 1
) X;

