
DROP TABLE IF EXISTS Person;
CREATE TABLE Person (
    PID INT NOT NULL,
    PN VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID)
);

DROP TABLE IF EXISTS Address;
CREATE TABLE Address (
    HID INT NOT NULL,
    HS VARCHAR(50) NOT NULL,
    HZ INT NOT NULL REFERENCES City(HZ),
    PRIMARY KEY (HID)
);

DROP TABLE IF EXISTS City;
CREATE TABLE City (
    HZ INT NOT NULL,
    HC VARCHAR(50) NOT NULL
    PRIMARY KEY (HZ)
);

DROP TABLE IF EXISTS Rental;
CREATE TABLE Rental (
    PID INT NOT NULL REFERENCES Person(PID),
    HID INT NOT NULL REFERENCES Address(HID),
    S INT NOT NULL
    PRIMARY KEY (PID, HID)
);
