-- First drop tables if they don't exists...
DROP TABLE IF EXISTS Reviews;
DROP TABLE IF EXISTS Grant;
DROP TABLE IF EXISTS Sponsor;
DROP TABLE IF EXISTS Monitors;
DROP TABLE IF EXISTS Party;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS ServeIn;
DROP TABLE IF EXISTS Participate;
DROP TABLE IF EXISTS Linking;
DROP TABLE IF EXISTS Opposes;
DROP TABLE IF EXISTS Asset;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Enemy;
DROP TABLE IF EXISTS People;

-- Create tables

CREATE TABLE People (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    Name VARCHAR(max),
    Address VARCHAR(max),
    Phone VARCHAR(8),
    DOB DATE,
    DOD DATE
);

CREATE TABLE Member (
    PID INT NOT NULL PRIMARY KEY REFERENCES People(ID),
    Start_date DATE NOT NULL
);

CREATE TABLE Enemy (
    PID INT NOT NULL PRIMARY KEY REFERENCES People(ID)
);

CREATE TABLE Asset (
    Name VARCHAR(max) NOT NULL,
    MemberID INT NOT NULL REFERENCES Member(PID),
    Detail VARCHAR(MAX),
    Uses VARCHAR(MAX),
    PRIMARY KEY (Name, MemberID)
);

CREATE TABLE Opposes (
    MID INT NOT NULL REFERENCES Member(PID),
    EID INT NOT NULL REFERENCES Enemy(PID),
    Start_date DATE,
    End_date Date,
    PRIMARY KEY (MID, EID)
);

CREATE TABLE Linking (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    Name VARCHAR(MAX),
    Type VARCHAR(MAX),
    Description VARCHAR(MAX)
);

CREATE TABLE Participate (
    PID INT NOT NULL REFERENCES People(ID),
    LID INT NOT NULL REFERENCES Linking(ID),
    PRIMARY KEY (PID, LID)
);

CREATE TABLE Role (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    Title VARCHAR(MAX)
);

CREATE TABLE ServeIn (
    RID INT NOT NULL REFERENCES Role(ID),
    MID INT NOT NULL REFERENCES Member(PID),
    Start_date DATE,
    End_date DATE,
    Salary INT,
    PRIMARY KEY (RID, MID)
);

CREATE TABLE Party (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    Country VARCHAR(MAX),
    Name VARCHAR(MAX)
);


CREATE TABLE Monitors (
    PartyID INT NOT NULL REFERENCES Party(ID),
    MID INT NOT NULL REFERENCES Member(PID),
    Start_date DATE NOT NULL,
    End_date DATE,
    PRIMARY KEY (PartyID, MID, Start_date)
);

CREATE TABLE Sponsor (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    Name VARCHAR(MAX),
    Address VARCHAR(MAX),
    Industry VARCHAR(MAX)
);

CREATE TABLE Grant (
    ID INT NOT NULL PRIMARY KEY SERIAL,
    SID INT NOT NULL REFERENCES Sponsor(ID),
    MID INT NOT NULL REFERENCES Member(PID),
    Date DATE NOT NULL,
    Amount INT,
    PayBack INT,

    UNIQUE(SID, MID, Date)
);

CREATE TABLE Reviews (
    GID INT NOT NULL REFERENCES Grant(ID),
    MID INT NOT NULL REFERENCES Member(PID)
    Date DATE,
    Grade CHAR(1),
    PRIMARY KEY (GID, MID)
);